// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CharacterCollider
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "character_id")]
        public ulong CharacterId;
        [DataMember(Name = "character")]
        public CharacterType Character;
        [DataMember(Name = "collider")]
        public ComplexCollider Collider;

        public CharacterCollider(
            ulong Id,
            ulong CharacterId,
            CharacterType Character,
            ComplexCollider Collider
        )
        {
            this.Id = Id;
            this.CharacterId = CharacterId;
            this.Character = Character;
            this.Collider = Collider;
        }

        public CharacterCollider()
        {
            this.Collider = new();
        }
    }
}
