// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ComplexCollider
    {
        [DataMember(Name = "convex_hulls")]
        public System.Collections.Generic.List<ConvexHullCollider> ConvexHulls;
        [DataMember(Name = "center_point")]
        public DbVector3 CenterPoint;
        [DataMember(Name = "bounding_radius")]
        public float BoundingRadius;

        public ComplexCollider(
            System.Collections.Generic.List<ConvexHullCollider> ConvexHulls,
            DbVector3 CenterPoint,
            float BoundingRadius
        )
        {
            this.ConvexHulls = ConvexHulls;
            this.CenterPoint = CenterPoint;
            this.BoundingRadius = BoundingRadius;
        }

        public ComplexCollider()
        {
            this.ConvexHulls = new();
            this.CenterPoint = new();
        }
    }
}
