// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConvexHullCollider
    {
        [DataMember(Name = "vertices_local")]
        public System.Collections.Generic.List<DbVector3> VerticesLocal;
        [DataMember(Name = "triangle_indices_local")]
        public System.Collections.Generic.List<int> TriangleIndicesLocal;
        [DataMember(Name = "margin")]
        public float Margin;
        [DataMember(Name = "collider_type")]
        public ConvexHullColliderType ColliderType;
        [DataMember(Name = "aabb_min_local")]
        public DbVector3 AabbMinLocal;
        [DataMember(Name = "aabb_max_local")]
        public DbVector3 AabbMaxLocal;

        public ConvexHullCollider(
            System.Collections.Generic.List<DbVector3> VerticesLocal,
            System.Collections.Generic.List<int> TriangleIndicesLocal,
            float Margin,
            ConvexHullColliderType ColliderType,
            DbVector3 AabbMinLocal,
            DbVector3 AabbMaxLocal
        )
        {
            this.VerticesLocal = VerticesLocal;
            this.TriangleIndicesLocal = TriangleIndicesLocal;
            this.Margin = Margin;
            this.ColliderType = ColliderType;
            this.AabbMinLocal = AabbMinLocal;
            this.AabbMaxLocal = AabbMaxLocal;
        }

        public ConvexHullCollider()
        {
            this.VerticesLocal = new();
            this.TriangleIndicesLocal = new();
            this.AabbMinLocal = new();
            this.AabbMaxLocal = new();
        }
    }
}
