// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DamageEffectInformation
    {
        [DataMember(Name = "base_damage")]
        public float BaseDamage;
        [DataMember(Name = "damage_type")]
        public DamageType DamageType;
        [DataMember(Name = "sender_name")]
        public string SenderName;
        [DataMember(Name = "target_name")]
        public string TargetName;

        public DamageEffectInformation(
            float BaseDamage,
            DamageType DamageType,
            string SenderName,
            string TargetName
        )
        {
            this.BaseDamage = BaseDamage;
            this.DamageType = DamageType;
            this.SenderName = SenderName;
            this.TargetName = TargetName;
        }

        public DamageEffectInformation()
        {
            this.DamageType = null!;
            this.SenderName = "";
            this.TargetName = "";
        }
    }
}
