// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DamageEffectInformation
    {
        [DataMember(Name = "base_damage")]
        public float BaseDamage;
        [DataMember(Name = "damage_type")]
        public DamageType DamageType;

        public DamageEffectInformation(
            float BaseDamage,
            DamageType DamageType
        )
        {
            this.BaseDamage = BaseDamage;
            this.DamageType = DamageType;
        }

        public DamageEffectInformation()
        {
            this.DamageType = null!;
        }
    }
}
