// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Game
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "in_progress")]
        public bool InProgress;
        [DataMember(Name = "max_players")]
        public uint MaxPlayers;
        [DataMember(Name = "current_players")]
        public uint CurrentPlayers;
        [DataMember(Name = "scoreboard")]
        public Scoreboard Scoreboard;

        public Game(
            uint Id,
            bool InProgress,
            uint MaxPlayers,
            uint CurrentPlayers,
            Scoreboard Scoreboard
        )
        {
            this.Id = Id;
            this.InProgress = InProgress;
            this.MaxPlayers = MaxPlayers;
            this.CurrentPlayers = CurrentPlayers;
            this.Scoreboard = Scoreboard;
        }

        public Game()
        {
            this.Scoreboard = new();
        }
    }
}
