// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class KillLog
    {
        [DataMember(Name = "game_id")]
        public uint GameId;
        [DataMember(Name = "killer_name")]
        public string KillerName;
        [DataMember(Name = "killed_name")]
        public string KilledName;

        public KillLog(
            uint GameId,
            string KillerName,
            string KilledName
        )
        {
            this.GameId = GameId;
            this.KillerName = KillerName;
            this.KilledName = KilledName;
        }

        public KillLog()
        {
            this.KillerName = "";
            this.KilledName = "";
        }
    }
}
