// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MapRespawnPoint
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation")]
        public DbRotation2 Rotation;

        public MapRespawnPoint(
            ulong Id,
            string Name,
            DbVector3 Position,
            DbRotation2 Rotation
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Position = Position;
            this.Rotation = Rotation;
        }

        public MapRespawnPoint()
        {
            this.Name = "";
            this.Position = new();
            this.Rotation = new();
        }
    }
}
