// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ModuleDebug
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "debug_on")]
        public bool DebugOn;

        public ModuleDebug(
            ulong Id,
            bool DebugOn
        )
        {
            this.Id = Id;
            this.DebugOn = DebugOn;
        }

        public ModuleDebug()
        {
        }
    }
}
