// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ScoreboardPlayer
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "score")]
        public ulong Score;

        public ScoreboardPlayer(
            SpacetimeDB.Identity Identity,
            string Name,
            ulong Score
        )
        {
            this.Identity = Identity;
            this.Name = Name;
            this.Score = Score;
        }

        public ScoreboardPlayer()
        {
            this.Name = "";
        }
    }
}
