// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HandleStatelessActionRequestMagicianHandler(ReducerEventContext ctx, SpacetimeDB.Types.StatelessActionRequestMagician request);
        public event HandleStatelessActionRequestMagicianHandler? OnHandleStatelessActionRequestMagician;

        public void HandleStatelessActionRequestMagician(SpacetimeDB.Types.StatelessActionRequestMagician request)
        {
            conn.InternalCallReducer(new Reducer.HandleStatelessActionRequestMagician(request));
        }

        public bool InvokeHandleStatelessActionRequestMagician(ReducerEventContext ctx, Reducer.HandleStatelessActionRequestMagician args)
        {
            if (OnHandleStatelessActionRequestMagician == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnHandleStatelessActionRequestMagician(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandleStatelessActionRequestMagician : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public StatelessActionRequestMagician Request;

            public HandleStatelessActionRequestMagician(StatelessActionRequestMagician Request)
            {
                this.Request = Request;
            }

            public HandleStatelessActionRequestMagician()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "handle_stateless_action_request_magician";
        }
    }
}
