// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HandleActionChangeRequestMagicianHandler(ReducerEventContext ctx, SpacetimeDB.Types.ActionRequestMagician request);
        public event HandleActionChangeRequestMagicianHandler? OnHandleActionChangeRequestMagician;

        public void HandleActionChangeRequestMagician(SpacetimeDB.Types.ActionRequestMagician request)
        {
            conn.InternalCallReducer(new Reducer.HandleActionChangeRequestMagician(request));
        }

        public bool InvokeHandleActionChangeRequestMagician(ReducerEventContext ctx, Reducer.HandleActionChangeRequestMagician args)
        {
            if (OnHandleActionChangeRequestMagician == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnHandleActionChangeRequestMagician(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandleActionChangeRequestMagician : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public ActionRequestMagician Request;

            public HandleActionChangeRequestMagician(ActionRequestMagician Request)
            {
                this.Request = Request;
            }

            public HandleActionChangeRequestMagician()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "handle_action_change_request_magician";
        }
    }
}
