// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HypnotiseHandler(ReducerEventContext ctx, SpacetimeDB.Types.HypnosisCameraInformation cameraInfo);
        public event HypnotiseHandler? OnHypnotise;

        public void Hypnotise(SpacetimeDB.Types.HypnosisCameraInformation cameraInfo)
        {
            conn.InternalCallReducer(new Reducer.Hypnotise(cameraInfo));
        }

        public bool InvokeHypnotise(ReducerEventContext ctx, Reducer.Hypnotise args)
        {
            if (OnHypnotise == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnHypnotise(
                ctx,
                args.CameraInfo
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Hypnotise : Reducer, IReducerArgs
        {
            [DataMember(Name = "camera_info")]
            public HypnosisCameraInformation CameraInfo;

            public Hypnotise(HypnosisCameraInformation CameraInfo)
            {
                this.CameraInfo = CameraInfo;
            }

            public Hypnotise()
            {
                this.CameraInfo = new();
            }

            string IReducerArgs.ReducerName => "hypnotise";
        }
    }
}
