// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MoveMagiciansLagTestHandler(ReducerEventContext ctx, SpacetimeDB.Types.MoveAllMagiciansTimer timer);
        public event MoveMagiciansLagTestHandler? OnMoveMagiciansLagTest;

        public void MoveMagiciansLagTest(SpacetimeDB.Types.MoveAllMagiciansTimer timer)
        {
            conn.InternalCallReducer(new Reducer.MoveMagiciansLagTest(timer));
        }

        public bool InvokeMoveMagiciansLagTest(ReducerEventContext ctx, Reducer.MoveMagiciansLagTest args)
        {
            if (OnMoveMagiciansLagTest == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMoveMagiciansLagTest(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MoveMagiciansLagTest : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public MoveAllMagiciansTimer Timer;

            public MoveMagiciansLagTest(MoveAllMagiciansTimer Timer)
            {
                this.Timer = Timer;
            }

            public MoveMagiciansLagTest()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "move_magicians_lag_test";
        }
    }
}
