// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RemoveCollisionEntryMagicianHandler(ReducerEventContext ctx, SpacetimeDB.Types.CollisionEntry entry, SpacetimeDB.Identity targetIdentity);
        public event RemoveCollisionEntryMagicianHandler? OnRemoveCollisionEntryMagician;

        public void RemoveCollisionEntryMagician(SpacetimeDB.Types.CollisionEntry entry, SpacetimeDB.Identity targetIdentity)
        {
            conn.InternalCallReducer(new Reducer.RemoveCollisionEntryMagician(entry, targetIdentity));
        }

        public bool InvokeRemoveCollisionEntryMagician(ReducerEventContext ctx, Reducer.RemoveCollisionEntryMagician args)
        {
            if (OnRemoveCollisionEntryMagician == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRemoveCollisionEntryMagician(
                ctx,
                args.Entry,
                args.TargetIdentity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RemoveCollisionEntryMagician : Reducer, IReducerArgs
        {
            [DataMember(Name = "entry")]
            public CollisionEntry Entry;
            [DataMember(Name = "target_identity")]
            public SpacetimeDB.Identity TargetIdentity;

            public RemoveCollisionEntryMagician(
                CollisionEntry Entry,
                SpacetimeDB.Identity TargetIdentity
            )
            {
                this.Entry = Entry;
                this.TargetIdentity = TargetIdentity;
            }

            public RemoveCollisionEntryMagician()
            {
                this.Entry = new();
            }

            string IReducerArgs.ReducerName => "remove_collision_entry_magician";
        }
    }
}
