// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartGameManualHandler(ReducerEventContext ctx);
        public event StartGameManualHandler? OnStartGameManual;

        public void StartGameManual()
        {
            conn.InternalCallReducer(new Reducer.StartGameManual());
        }

        public bool InvokeStartGameManual(ReducerEventContext ctx, Reducer.StartGameManual args)
        {
            if (OnStartGameManual == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStartGameManual(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartGameManual : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "start_game_manual";
        }
    }
}
