// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TakeArtificalDamageHandler(ReducerEventContext ctx);
        public event TakeArtificalDamageHandler? OnTakeArtificalDamage;

        public void TakeArtificalDamage()
        {
            conn.InternalCallReducer(new Reducer.TakeArtificalDamage(), this.SetCallReducerFlags.TakeArtificalDamageFlags);
        }

        public bool InvokeTakeArtificalDamage(ReducerEventContext ctx, Reducer.TakeArtificalDamage args)
        {
            if (OnTakeArtificalDamage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTakeArtificalDamage(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TakeArtificalDamage : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "take_artifical_damage";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TakeArtificalDamageFlags;
        public void TakeArtificalDamage(CallReducerFlags flags) => TakeArtificalDamageFlags = flags;
    }
}
