// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TakeArtificalDustHandler(ReducerEventContext ctx);
        public event TakeArtificalDustHandler? OnTakeArtificalDust;

        public void TakeArtificalDust()
        {
            conn.InternalCallReducer(new Reducer.TakeArtificalDust());
        }

        public bool InvokeTakeArtificalDust(ReducerEventContext ctx, Reducer.TakeArtificalDust args)
        {
            if (OnTakeArtificalDust == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTakeArtificalDust(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TakeArtificalDust : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "take_artifical_dust";
        }
    }
}
