// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TestJoinAndStartGameSinglePlayerHandler(ReducerEventContext ctx);
        public event TestJoinAndStartGameSinglePlayerHandler? OnTestJoinAndStartGameSinglePlayer;

        public void TestJoinAndStartGameSinglePlayer()
        {
            conn.InternalCallReducer(new Reducer.TestJoinAndStartGameSinglePlayer());
        }

        public bool InvokeTestJoinAndStartGameSinglePlayer(ReducerEventContext ctx, Reducer.TestJoinAndStartGameSinglePlayer args)
        {
            if (OnTestJoinAndStartGameSinglePlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTestJoinAndStartGameSinglePlayer(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TestJoinAndStartGameSinglePlayer : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "test_join_and_start_game_single_player";
        }
    }
}
