// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DebugTableHandle : RemoteTableHandle<EventContext, ModuleDebug>
        {
            protected override string RemoteTableName => "debug_table";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ModuleDebug row) => row.Id;

                public IdUniqueIndex(DebugTableHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal DebugTableHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ModuleDebug row) => row.Id;
        }

        public readonly DebugTableHandle DebugTable;
    }

    public sealed class DebugTableCols
    {
        public global::SpacetimeDB.Col<ModuleDebug, ulong> Id { get; }
        public global::SpacetimeDB.Col<ModuleDebug, bool> DebugOn { get; }

        public DebugTableCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ModuleDebug, ulong>(tableName, "id");
            DebugOn = new global::SpacetimeDB.Col<ModuleDebug, bool>(tableName, "debug_on");
        }
    }

    public sealed class DebugTableIxCols
    {
        public global::SpacetimeDB.IxCol<ModuleDebug, ulong> Id { get; }

        public DebugTableIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ModuleDebug, ulong>(tableName, "id");
        }
    }
}
