// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameTimersHandle : RemoteTableHandle<EventContext, GameTimersTimer>
        {
            protected override string RemoteTableName => "game_timers";

            public sealed class GameIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(GameTimersTimer row) => row.GameId;

                public GameIdUniqueIndex(GameTimersHandle table) : base(table) { }
            }

            public readonly GameIdUniqueIndex GameId;

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(GameTimersTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(GameTimersHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal GameTimersHandle(DbConnection conn) : base(conn)
            {
                GameId = new(this);
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(GameTimersTimer row) => row.ScheduledId;
        }

        public readonly GameTimersHandle GameTimers;
    }

    public sealed class GameTimersCols
    {
        public global::SpacetimeDB.Col<GameTimersTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<GameTimersTimer, uint> GameId { get; }
        public global::SpacetimeDB.Col<GameTimersTimer, SpacetimeDB.ScheduleAt> ScheduledAt { get; }

        public GameTimersCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<GameTimersTimer, ulong>(tableName, "scheduled_id");
            GameId = new global::SpacetimeDB.Col<GameTimersTimer, uint>(tableName, "game_id");
            ScheduledAt = new global::SpacetimeDB.Col<GameTimersTimer, SpacetimeDB.ScheduleAt>(tableName, "scheduled_at");
        }
    }

    public sealed class GameTimersIxCols
    {
        public global::SpacetimeDB.IxCol<GameTimersTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.IxCol<GameTimersTimer, uint> GameId { get; }

        public GameTimersIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<GameTimersTimer, ulong>(tableName, "scheduled_id");
            GameId = new global::SpacetimeDB.IxCol<GameTimersTimer, uint>(tableName, "game_id");
        }
    }
}
