// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GravityMagicianHandle : RemoteTableHandle<EventContext, GravityTimerMagician>
        {
            protected override string RemoteTableName => "gravity_magician";

            public sealed class GameIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(GravityTimerMagician row) => row.GameId;

                public GameIdUniqueIndex(GravityMagicianHandle table) : base(table) { }
            }

            public readonly GameIdUniqueIndex GameId;

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(GravityTimerMagician row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(GravityMagicianHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal GravityMagicianHandle(DbConnection conn) : base(conn)
            {
                GameId = new(this);
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(GravityTimerMagician row) => row.ScheduledId;
        }

        public readonly GravityMagicianHandle GravityMagician;
    }

    public sealed class GravityMagicianCols
    {
        public global::SpacetimeDB.Col<GravityTimerMagician, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<GravityTimerMagician, SpacetimeDB.ScheduleAt> ScheduledAt { get; }
        public global::SpacetimeDB.Col<GravityTimerMagician, float> TickRate { get; }
        public global::SpacetimeDB.Col<GravityTimerMagician, float> Gravity { get; }
        public global::SpacetimeDB.Col<GravityTimerMagician, uint> GameId { get; }

        public GravityMagicianCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<GravityTimerMagician, ulong>(tableName, "scheduled_id");
            ScheduledAt = new global::SpacetimeDB.Col<GravityTimerMagician, SpacetimeDB.ScheduleAt>(tableName, "scheduled_at");
            TickRate = new global::SpacetimeDB.Col<GravityTimerMagician, float>(tableName, "tick_rate");
            Gravity = new global::SpacetimeDB.Col<GravityTimerMagician, float>(tableName, "gravity");
            GameId = new global::SpacetimeDB.Col<GravityTimerMagician, uint>(tableName, "game_id");
        }
    }

    public sealed class GravityMagicianIxCols
    {
        public global::SpacetimeDB.IxCol<GravityTimerMagician, ulong> ScheduledId { get; }
        public global::SpacetimeDB.IxCol<GravityTimerMagician, uint> GameId { get; }

        public GravityMagicianIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<GravityTimerMagician, ulong>(tableName, "scheduled_id");
            GameId = new global::SpacetimeDB.IxCol<GravityTimerMagician, uint>(tableName, "game_id");
        }
    }
}
