// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class HandleMagicianTimersTimerHandle : RemoteTableHandle<EventContext, HandleMagicianTimersTimer>
        {
            protected override string RemoteTableName => "handle_magician_timers_timer";

            public sealed class GameIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(HandleMagicianTimersTimer row) => row.GameId;

                public GameIdUniqueIndex(HandleMagicianTimersTimerHandle table) : base(table) { }
            }

            public readonly GameIdUniqueIndex GameId;

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(HandleMagicianTimersTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(HandleMagicianTimersTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal HandleMagicianTimersTimerHandle(DbConnection conn) : base(conn)
            {
                GameId = new(this);
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(HandleMagicianTimersTimer row) => row.ScheduledId;
        }

        public readonly HandleMagicianTimersTimerHandle HandleMagicianTimersTimer;
    }

    public sealed class HandleMagicianTimersTimerCols
    {
        public global::SpacetimeDB.Col<HandleMagicianTimersTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<HandleMagicianTimersTimer, SpacetimeDB.ScheduleAt> ScheduledAt { get; }
        public global::SpacetimeDB.Col<HandleMagicianTimersTimer, float> TickRate { get; }
        public global::SpacetimeDB.Col<HandleMagicianTimersTimer, uint> GameId { get; }

        public HandleMagicianTimersTimerCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<HandleMagicianTimersTimer, ulong>(tableName, "scheduled_id");
            ScheduledAt = new global::SpacetimeDB.Col<HandleMagicianTimersTimer, SpacetimeDB.ScheduleAt>(tableName, "scheduled_at");
            TickRate = new global::SpacetimeDB.Col<HandleMagicianTimersTimer, float>(tableName, "tick_rate");
            GameId = new global::SpacetimeDB.Col<HandleMagicianTimersTimer, uint>(tableName, "game_id");
        }
    }

    public sealed class HandleMagicianTimersTimerIxCols
    {
        public global::SpacetimeDB.IxCol<HandleMagicianTimersTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.IxCol<HandleMagicianTimersTimer, uint> GameId { get; }

        public HandleMagicianTimersTimerIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<HandleMagicianTimersTimer, ulong>(tableName, "scheduled_id");
            GameId = new global::SpacetimeDB.IxCol<HandleMagicianTimersTimer, uint>(tableName, "game_id");
        }
    }
}
