// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class KillLogsHandle : RemoteEventTableHandle<EventContext, KillLog>
        {
            protected override string RemoteTableName => "kill_logs";

            internal KillLogsHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly KillLogsHandle KillLogs;
    }

    public sealed class KillLogsCols
    {
        public global::SpacetimeDB.Col<KillLog, uint> GameId { get; }
        public global::SpacetimeDB.Col<KillLog, string> KillerName { get; }
        public global::SpacetimeDB.Col<KillLog, string> KilledName { get; }

        public KillLogsCols(string tableName)
        {
            GameId = new global::SpacetimeDB.Col<KillLog, uint>(tableName, "game_id");
            KillerName = new global::SpacetimeDB.Col<KillLog, string>(tableName, "killer_name");
            KilledName = new global::SpacetimeDB.Col<KillLog, string>(tableName, "killed_name");
        }
    }

    public sealed class KillLogsIxCols
    {

        public KillLogsIxCols(string tableName)
        {
        }
    }
}
