// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LoggedInPlayersHandle : RemoteTableHandle<EventContext, Player>
        {
            protected override string RemoteTableName => "logged_in_players";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Player row) => row.Id;

                public IdUniqueIndex(LoggedInPlayersHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Player row) => row.Identity;

                public IdentityUniqueIndex(LoggedInPlayersHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal LoggedInPlayersHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Identity = new(this);
            }

            protected override object GetPrimaryKey(Player row) => row.Identity;
        }

        public readonly LoggedInPlayersHandle LoggedInPlayers;
    }

    public sealed class LoggedInPlayersCols
    {
        public global::SpacetimeDB.Col<Player, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<Player, ulong> Id { get; }
        public global::SpacetimeDB.Col<Player, string> Name { get; }

        public LoggedInPlayersCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<Player, SpacetimeDB.Identity>(tableName, "identity");
            Id = new global::SpacetimeDB.Col<Player, ulong>(tableName, "id");
            Name = new global::SpacetimeDB.Col<Player, string>(tableName, "name");
        }
    }

    public sealed class LoggedInPlayersIxCols
    {
        public global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.IxCol<Player, ulong> Id { get; }

        public LoggedInPlayersIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity>(tableName, "identity");
            Id = new global::SpacetimeDB.IxCol<Player, ulong>(tableName, "id");
        }
    }
}
