// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MapHandle : RemoteTableHandle<EventContext, Map>
        {
            protected override string RemoteTableName => "map";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Map row) => row.Id;

                public IdUniqueIndex(MapHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Map row) => row.Name;

                public NameUniqueIndex(MapHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            internal MapHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Name = new(this);
            }

            protected override object GetPrimaryKey(Map row) => row.Id;
        }

        public readonly MapHandle Map;
    }

    public sealed class MapCols
    {
        public global::SpacetimeDB.Col<Map, ulong> Id { get; }
        public global::SpacetimeDB.Col<Map, string> Name { get; }
        public global::SpacetimeDB.Col<Map, ComplexCollider> Collider { get; }

        public MapCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Map, ulong>(tableName, "id");
            Name = new global::SpacetimeDB.Col<Map, string>(tableName, "name");
            Collider = new global::SpacetimeDB.Col<Map, ComplexCollider>(tableName, "collider");
        }
    }

    public sealed class MapIxCols
    {
        public global::SpacetimeDB.IxCol<Map, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Map, string> Name { get; }

        public MapIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Map, ulong>(tableName, "id");
            Name = new global::SpacetimeDB.IxCol<Map, string>(tableName, "name");
        }
    }
}
