// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MoveAllMagiciansHandle : RemoteTableHandle<EventContext, MoveAllMagiciansTimer>
        {
            protected override string RemoteTableName => "move_all_magicians";

            public sealed class GameIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(MoveAllMagiciansTimer row) => row.GameId;

                public GameIdUniqueIndex(MoveAllMagiciansHandle table) : base(table) { }
            }

            public readonly GameIdUniqueIndex GameId;

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MoveAllMagiciansTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(MoveAllMagiciansHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal MoveAllMagiciansHandle(DbConnection conn) : base(conn)
            {
                GameId = new(this);
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(MoveAllMagiciansTimer row) => row.ScheduledId;
        }

        public readonly MoveAllMagiciansHandle MoveAllMagicians;
    }

    public sealed class MoveAllMagiciansCols
    {
        public global::SpacetimeDB.Col<MoveAllMagiciansTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<MoveAllMagiciansTimer, SpacetimeDB.ScheduleAt> ScheduledAt { get; }
        public global::SpacetimeDB.Col<MoveAllMagiciansTimer, float> TickRate { get; }
        public global::SpacetimeDB.Col<MoveAllMagiciansTimer, uint> GameId { get; }

        public MoveAllMagiciansCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<MoveAllMagiciansTimer, ulong>(tableName, "scheduled_id");
            ScheduledAt = new global::SpacetimeDB.Col<MoveAllMagiciansTimer, SpacetimeDB.ScheduleAt>(tableName, "scheduled_at");
            TickRate = new global::SpacetimeDB.Col<MoveAllMagiciansTimer, float>(tableName, "tick_rate");
            GameId = new global::SpacetimeDB.Col<MoveAllMagiciansTimer, uint>(tableName, "game_id");
        }
    }

    public sealed class MoveAllMagiciansIxCols
    {
        public global::SpacetimeDB.IxCol<MoveAllMagiciansTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.IxCol<MoveAllMagiciansTimer, uint> GameId { get; }

        public MoveAllMagiciansIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<MoveAllMagiciansTimer, ulong>(tableName, "scheduled_id");
            GameId = new global::SpacetimeDB.IxCol<MoveAllMagiciansTimer, uint>(tableName, "game_id");
        }
    }
}
