// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MyGameHandle : RemoteTableHandle<EventContext, Game>
        {
            protected override string RemoteTableName => "my_game";

            internal MyGameHandle(DbConnection conn) : base(conn)
            {
            }

            protected override object GetPrimaryKey(Game row) => row.Id;
        }

        public readonly MyGameHandle MyGame;
    }

    public sealed class MyGameCols
    {
        public global::SpacetimeDB.Col<Game, uint> Id { get; }
        public global::SpacetimeDB.Col<Game, bool> InProgress { get; }
        public global::SpacetimeDB.Col<Game, uint> MaxPlayers { get; }
        public global::SpacetimeDB.Col<Game, uint> CurrentPlayers { get; }
        public global::SpacetimeDB.Col<Game, Scoreboard> Scoreboard { get; }

        public MyGameCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Game, uint>(tableName, "id");
            InProgress = new global::SpacetimeDB.Col<Game, bool>(tableName, "in_progress");
            MaxPlayers = new global::SpacetimeDB.Col<Game, uint>(tableName, "max_players");
            CurrentPlayers = new global::SpacetimeDB.Col<Game, uint>(tableName, "current_players");
            Scoreboard = new global::SpacetimeDB.Col<Game, Scoreboard>(tableName, "scoreboard");
        }
    }

    public sealed class MyGameIxCols
    {
        public global::SpacetimeDB.IxCol<Game, uint> Id { get; }

        public MyGameIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Game, uint>(tableName, "id");
        }
    }
}
