// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerEffectsHandle : RemoteTableHandle<EventContext, PlayerEffect>
        {
            protected override string RemoteTableName => "player_effects";

            public sealed class GameIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(PlayerEffect row) => row.GameId;

                public GameIdIndex(PlayerEffectsHandle table) : base(table) { }
            }

            public readonly GameIdIndex GameId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerEffect row) => row.Id;

                public IdUniqueIndex(PlayerEffectsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class SenderIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerEffect row) => row.SenderId;

                public SenderIdIndex(PlayerEffectsHandle table) : base(table) { }
            }

            public readonly SenderIdIndex SenderId;

            public sealed class TargetAndTypeIndex : BTreeIndexBase<(ulong TargetId, EffectType EffectType)>
            {
                protected override (ulong TargetId, EffectType EffectType) GetKey(PlayerEffect row) => (row.TargetId, row.EffectType);

                public TargetAndTypeIndex(PlayerEffectsHandle table) : base(table) { }
            }

            public readonly TargetAndTypeIndex TargetAndType;

            public sealed class TargetIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerEffect row) => row.TargetId;

                public TargetIdIndex(PlayerEffectsHandle table) : base(table) { }
            }

            public readonly TargetIdIndex TargetId;

            public sealed class TargetSenderAndTypeIndex : BTreeIndexBase<(ulong TargetId, ulong SenderId, EffectType EffectType)>
            {
                protected override (ulong TargetId, ulong SenderId, EffectType EffectType) GetKey(PlayerEffect row) => (row.TargetId, row.SenderId, row.EffectType);

                public TargetSenderAndTypeIndex(PlayerEffectsHandle table) : base(table) { }
            }

            public readonly TargetSenderAndTypeIndex TargetSenderAndType;

            internal PlayerEffectsHandle(DbConnection conn) : base(conn)
            {
                GameId = new(this);
                Id = new(this);
                SenderId = new(this);
                TargetAndType = new(this);
                TargetId = new(this);
                TargetSenderAndType = new(this);
            }

            protected override object GetPrimaryKey(PlayerEffect row) => row.Id;
        }

        public readonly PlayerEffectsHandle PlayerEffects;
    }

    public sealed class PlayerEffectsCols
    {
        public global::SpacetimeDB.Col<PlayerEffect, ulong> Id { get; }
        public global::SpacetimeDB.Col<PlayerEffect, ulong> TargetId { get; }
        public global::SpacetimeDB.Col<PlayerEffect, ulong> SenderId { get; }
        public global::SpacetimeDB.Col<PlayerEffect, uint> GameId { get; }
        public global::SpacetimeDB.Col<PlayerEffect, Effect> EffectInfo { get; }
        public global::SpacetimeDB.Col<PlayerEffect, EffectType> EffectType { get; }

        public PlayerEffectsCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<PlayerEffect, ulong>(tableName, "id");
            TargetId = new global::SpacetimeDB.Col<PlayerEffect, ulong>(tableName, "target_id");
            SenderId = new global::SpacetimeDB.Col<PlayerEffect, ulong>(tableName, "sender_id");
            GameId = new global::SpacetimeDB.Col<PlayerEffect, uint>(tableName, "game_id");
            EffectInfo = new global::SpacetimeDB.Col<PlayerEffect, Effect>(tableName, "effect_info");
            EffectType = new global::SpacetimeDB.Col<PlayerEffect, EffectType>(tableName, "effect_type");
        }
    }

    public sealed class PlayerEffectsIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerEffect, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<PlayerEffect, ulong> TargetId { get; }
        public global::SpacetimeDB.IxCol<PlayerEffect, ulong> SenderId { get; }
        public global::SpacetimeDB.IxCol<PlayerEffect, uint> GameId { get; }
        public global::SpacetimeDB.IxCol<PlayerEffect, EffectType> EffectType { get; }

        public PlayerEffectsIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<PlayerEffect, ulong>(tableName, "id");
            TargetId = new global::SpacetimeDB.IxCol<PlayerEffect, ulong>(tableName, "target_id");
            SenderId = new global::SpacetimeDB.IxCol<PlayerEffect, ulong>(tableName, "sender_id");
            GameId = new global::SpacetimeDB.IxCol<PlayerEffect, uint>(tableName, "game_id");
            EffectType = new global::SpacetimeDB.IxCol<PlayerEffect, EffectType>(tableName, "effect_type");
        }
    }
}
