// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerEffectsTableTimerHandle : RemoteTableHandle<EventContext, PlayerEffectsTableTimer>
        {
            protected override string RemoteTableName => "player_effects_table_timer";

            public sealed class GameIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(PlayerEffectsTableTimer row) => row.GameId;

                public GameIdUniqueIndex(PlayerEffectsTableTimerHandle table) : base(table) { }
            }

            public readonly GameIdUniqueIndex GameId;

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerEffectsTableTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(PlayerEffectsTableTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal PlayerEffectsTableTimerHandle(DbConnection conn) : base(conn)
            {
                GameId = new(this);
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(PlayerEffectsTableTimer row) => row.ScheduledId;
        }

        public readonly PlayerEffectsTableTimerHandle PlayerEffectsTableTimer;
    }

    public sealed class PlayerEffectsTableTimerCols
    {
        public global::SpacetimeDB.Col<PlayerEffectsTableTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<PlayerEffectsTableTimer, SpacetimeDB.ScheduleAt> ScheduledAt { get; }
        public global::SpacetimeDB.Col<PlayerEffectsTableTimer, float> TickRate { get; }
        public global::SpacetimeDB.Col<PlayerEffectsTableTimer, uint> GameId { get; }

        public PlayerEffectsTableTimerCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<PlayerEffectsTableTimer, ulong>(tableName, "scheduled_id");
            ScheduledAt = new global::SpacetimeDB.Col<PlayerEffectsTableTimer, SpacetimeDB.ScheduleAt>(tableName, "scheduled_at");
            TickRate = new global::SpacetimeDB.Col<PlayerEffectsTableTimer, float>(tableName, "tick_rate");
            GameId = new global::SpacetimeDB.Col<PlayerEffectsTableTimer, uint>(tableName, "game_id");
        }
    }

    public sealed class PlayerEffectsTableTimerIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerEffectsTableTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.IxCol<PlayerEffectsTableTimer, uint> GameId { get; }

        public PlayerEffectsTableTimerIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<PlayerEffectsTableTimer, ulong>(tableName, "scheduled_id");
            GameId = new global::SpacetimeDB.IxCol<PlayerEffectsTableTimer, uint>(tableName, "game_id");
        }
    }
}
