// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RespawnTimersHandle : RemoteTableHandle<EventContext, RespawnTimersTimer>
        {
            protected override string RemoteTableName => "respawn_timers";

            public sealed class GameIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(RespawnTimersTimer row) => row.GameId;

                public GameIdIndex(RespawnTimersHandle table) : base(table) { }
            }

            public readonly GameIdIndex GameId;

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(RespawnTimersTimer row) => row.Identity;

                public IdentityUniqueIndex(RespawnTimersHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RespawnTimersTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(RespawnTimersHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal RespawnTimersHandle(DbConnection conn) : base(conn)
            {
                GameId = new(this);
                Identity = new(this);
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(RespawnTimersTimer row) => row.ScheduledId;
        }

        public readonly RespawnTimersHandle RespawnTimers;
    }

    public sealed class RespawnTimersCols
    {
        public global::SpacetimeDB.Col<RespawnTimersTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<RespawnTimersTimer, uint> GameId { get; }
        public global::SpacetimeDB.Col<RespawnTimersTimer, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<RespawnTimersTimer, SpacetimeDB.ScheduleAt> ScheduledAt { get; }

        public RespawnTimersCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<RespawnTimersTimer, ulong>(tableName, "scheduled_id");
            GameId = new global::SpacetimeDB.Col<RespawnTimersTimer, uint>(tableName, "game_id");
            Identity = new global::SpacetimeDB.Col<RespawnTimersTimer, SpacetimeDB.Identity>(tableName, "identity");
            ScheduledAt = new global::SpacetimeDB.Col<RespawnTimersTimer, SpacetimeDB.ScheduleAt>(tableName, "scheduled_at");
        }
    }

    public sealed class RespawnTimersIxCols
    {
        public global::SpacetimeDB.IxCol<RespawnTimersTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.IxCol<RespawnTimersTimer, uint> GameId { get; }
        public global::SpacetimeDB.IxCol<RespawnTimersTimer, SpacetimeDB.Identity> Identity { get; }

        public RespawnTimersIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<RespawnTimersTimer, ulong>(tableName, "scheduled_id");
            GameId = new global::SpacetimeDB.IxCol<RespawnTimersTimer, uint>(tableName, "game_id");
            Identity = new global::SpacetimeDB.IxCol<RespawnTimersTimer, SpacetimeDB.Identity>(tableName, "identity");
        }
    }
}
