// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UnavailableRequestEventHandle : RemoteEventTableHandle<EventContext, UnavailableRequestEvent>
        {
            protected override string RemoteTableName => "unavailable_request_event";

            internal UnavailableRequestEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly UnavailableRequestEventHandle UnavailableRequestEvent;
    }

    public sealed class UnavailableRequestEventCols
    {
        public global::SpacetimeDB.Col<UnavailableRequestEvent, SpacetimeDB.Identity> Identity { get; }

        public UnavailableRequestEventCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<UnavailableRequestEvent, SpacetimeDB.Identity>(tableName, "identity");
        }
    }

    public sealed class UnavailableRequestEventIxCols
    {

        public UnavailableRequestEventIxCols(string tableName)
        {
        }
    }
}
