// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UnavailableRequestInterruptEventHandle : RemoteEventTableHandle<EventContext, UnavailableRequestInterruptEvent>
        {
            protected override string RemoteTableName => "unavailable_request_interrupt_event";

            internal UnavailableRequestInterruptEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly UnavailableRequestInterruptEventHandle UnavailableRequestInterruptEvent;
    }

    public sealed class UnavailableRequestInterruptEventCols
    {
        public global::SpacetimeDB.Col<UnavailableRequestInterruptEvent, SpacetimeDB.Identity> Identity { get; }

        public UnavailableRequestInterruptEventCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<UnavailableRequestInterruptEvent, SpacetimeDB.Identity>(tableName, "identity");
        }
    }

    public sealed class UnavailableRequestInterruptEventIxCols
    {

        public UnavailableRequestInterruptEventIxCols(string tableName)
        {
        }
    }
}
