// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UnitTestModeHandle : RemoteTableHandle<EventContext, UnitTestMode>
        {
            protected override string RemoteTableName => "unit_test_mode";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(UnitTestMode row) => row.Id;

                public IdUniqueIndex(UnitTestModeHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal UnitTestModeHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(UnitTestMode row) => row.Id;
        }

        public readonly UnitTestModeHandle UnitTestMode;
    }

    public sealed class UnitTestModeCols
    {
        public global::SpacetimeDB.Col<UnitTestMode, uint> Id { get; }
        public global::SpacetimeDB.Col<UnitTestMode, bool> Enabled { get; }

        public UnitTestModeCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<UnitTestMode, uint>(tableName, "id");
            Enabled = new global::SpacetimeDB.Col<UnitTestMode, bool>(tableName, "enabled");
        }
    }

    public sealed class UnitTestModeIxCols
    {
        public global::SpacetimeDB.IxCol<UnitTestMode, uint> Id { get; }

        public UnitTestModeIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<UnitTestMode, uint>(tableName, "id");
        }
    }
}
